<?php

require_once __DIR__ . "/config.php";

set_include_path(get_include_path() . PATH_SEPARATOR . __DIR__."/../civicrm/");
set_include_path(get_include_path() . PATH_SEPARATOR . __DIR__."/../civicrm/packages");

require_once conf_path()."/civicrm.settings.php";
require_once "CRM/Core/Config.php";


function donationreceipts_civicrm_tabs( &$tabs, $contactID ) {
    $config =& CRM_Core_Config::singleton( );

    $tabs[] = array( 'id'    => 'foebudTab',
                     'url'   => dirname($config->resourceBase) 
                              . "/donationreceipts/scripts/contact_tab.php?contact_id=$contactID&conf_path="
                              . urlencode(realpath(conf_path())),
                     'title' => FOEBUD_MENU_NAME,
                     'weight' => 300
                     );
}


